# Generated by Django 2.0.1 on 2018-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guessingGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guessthis',
            name='hasBeenGuessed',
            field=models.BooleanField(default=False),
        ),
    ]
